# Generated by Django 3.0.3 on 2020-04-27 00:13

import apps.forms_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[apps.forms_app.models.validateLengthGreaterThanTwo])),
                ('desc', models.TextField(max_length=1000)),
                ('color', models.CharField(max_length=45)),
                ('age', models.IntegerField(validators=[apps.forms_app.models.validateIntegerLessThan200, apps.forms_app.models.validateIntegerGreaterThan1])),
                ('weight', models.IntegerField(validators=[apps.forms_app.models.validateIntegerLessThan200])),
                ('height', models.IntegerField(validators=[apps.forms_app.models.validateIntegerLessThan200])),
                ('animal_type', models.CharField(max_length=100, validators=[apps.forms_app.models.validateLengthGreaterThanTwo])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
